version: "3.8"
services:
  mysqldb:
    image: "mysql:8.4"
    restart: always
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}
    networks:
      - springapimysql-net  
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
networks:
  springapimysql-net: