version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://viaduct.proxy.rlwy.net:28602/railway
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=TZsteRURTLBMtAPHcFTWRtyJVtwdrFib
    ports:
      - "8080:8080"
