version: '3.8'

services:
  # Nginx Proxy Reverso
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - frontend
      - backend
      - python-api
    restart: unless-stopped
    networks:
      - app-network

  # Backend Java (Spring Boot)
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/${PG_DATABASE:-arboviroses}
      - SPRING_DATASOURCE_USERNAME=${PG_USER:-postgres}
      - SPRING_DATASOURCE_PASSWORD=${PG_PASSWORD:-password}
      - SPRING_PROFILES_ACTIVE=docker
    expose:
      - "8080"
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - app-network

  # Frontend React/Vite
  frontend:
    build:
      context: ../ArbovirosesFront
      dockerfile: Dockerfile
    expose:
      - "3000"
    environment:
      - VITE_API_URL=http://arbomonitor/api
      - VITE_PYTHON_API_URL=http://arbomonitor/python-api
    restart: unless-stopped
    networks:
      - app-network

  # API Python (FastAPI)
  python-api:
    build:
      context: ../Arboviroses-python
      dockerfile: Dockerfile
    expose:
      - "8000"
    restart: unless-stopped
    networks:
      - app-network

  # Banco de Dados PostgreSQL
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=${PG_DATABASE:-arboviroses}
      - POSTGRES_USER=${PG_USER:-postgres}
      - POSTGRES_PASSWORD=${PG_PASSWORD:-password}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - "5432"
    restart: unless-stopped
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
